### ISSUE TITLE
Relay setup

### ISSUE THREAD

**Issue by amirjalaliafshar** [johnpierson/Relay#10]
Hi John,
I had Relay on my previous laptop, but recently I have changed it and relay icon is not appearing on Revit ribbon,
I am using Revit 2021.4.
I have download the relay from initial release, unzipped it and replace the .dll with the latest publish
I have unblocked both .addin and .dll
the folder structure in Revit addin 2021 folder is : Relay(folder), relay.addin - > inside the relay folder I have : Relay graph(Folder), relay.dll
Previously with the same setup I receive a msg on Revit that " do you want to load this addin" and then it appeared on the ribbon. but right now after all of these setup nothing happens on Revit.

Do you know where is the problem?

**Comment by paulmst** [comment]
@amirjalaliafshar 
I just tested this and the only difference in my set up is that my folder is called '**RelayGraphs**' rather than '**Relay graph**' as you mention above.

I tried changing my folder to '**Relay graph**' which caused it to break, so I believe it needs to be '**RelayGraphs**' in order to work.

Hope this solves it?

**Comment by ChrisDHME** [comment]
I'm running into the same issue for installing it on revit 2023. However the suggestion from @paulmst does not work since there is no "relay graphs" folder anymore, renaming it to that doesn't help either
