### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by NawafKi** [johnpierson/Relay#8]
Is There anyway to hide the directory path in the tooltip ?

**Comment by johnpierson** [comment]
not at this time. we can try looking at adding an option in future releases that reads the description of the dynamo graph. (new feature in Dynamo 2.12)

**Comment by brencass** [comment]
@johnpierson Have a look at my recent fork variation that could help to add this feature to all Dynamo Scripts irrespective of if they are Dynamo 2.12 or not. The dynamo 2.12 description could be additionally added. It does require the scripts to having a specific "note" within the script to work in a similar way to using a scripting template that includes additional notes for information purposes. Though if it does not find this it will revert back to original implementation.

Note: 

- Do not take all of the full branch because i modified the project file to include nuget packages.
- You will need to add "Newtonsoft.Json" reference.
- You will need to add "Microsoft.Csharp" reference.
- I have added/modified scripts to show how this can be added to a file.

Image 1:
![image](https://user-images.githubusercontent.com/14090637/147843218-c49d416f-60af-458d-abd6-d53277896978.png)

Image 2: 
![image](https://user-images.githubusercontent.com/14090637/147843232-43e866f7-9da8-423d-8382-1e8af2cea748.png)

Folder Organisation for the above two image:
![image](https://user-images.githubusercontent.com/14090637/147843369-da1eaddb-7e03-43a4-be43-88262f2172c6.png)


Example Data within Script:
![image](https://user-images.githubusercontent.com/14090637/147843273-12ec66e5-5ea8-4bd1-86a0-2efe9bfca1e5.png)



My fork variation: https://github.com/brencass/Relay/tree/ReadsDescriptionFromWithinFile

**Comment by johnpierson** [comment]
Hmm. I'll have to take a look and I like the idea. 


However, I would really like to support the 2.12 properties first, the custom note second and default file path if those two are not present

**Comment by brencass** [comment]
I agree that the new 2.12 feature for description property should take precedence over other things but what I have added should give a good enough starting part :)

**Comment by johnpierson** [comment]
Definitely! I appreciate your contribution too and I'll get that pulled over along with the other options. 😁 

happy new year!

**Comment by brencass** [comment]
No worries, good to contribute a thought with the code implementation :)

Happy new year to you too!

**Comment by brencass** [comment]
Added the ability for Dynamo 2.12 and above description to be used and is used as a preference if it is not empty("")  on my fork :) 

https://github.com/brencass/Relay/tree/ReadsDescriptionFromWithinFile

**Comment by johnpierson** [comment]
@brencass I checked on this and the description in the DYN json exists (and persists) all the way back to at least Dynamo 2.0.4 
![image](https://user-images.githubusercontent.com/15744724/148441903-0805b873-baa0-4321-8593-7b71e4cba38d.png)
_in this image i added that description in 2.12, opened in 2.0.4 and saved it and it lasts throughout_

The UI modification of it was introduced in 2.12 making it easier. For older versions if you edit the .dyn as text it works.

This would mean that the modern description could be the tooltip (and the URL parameter introduced in 2.12 can be the F1 help in the future).

Extending this with the notes is interesting, but this functionality being built-in to the `.dyn` itself is what is very interesting to me.

**Comment by brencass** [comment]
@johnpierson This changes the game a little bit and maybe it should "check" if it can find the description property instead of the dynamo version. Then if this is null or " " then it will use the notes and as a last resort is the original way.

Adding the F1 help part should be a easy to add into the code.

I just tried to see if you add other properties manually into a dyn file if they are kept past a re-save, bad news is that they are not :(.

**Comment by johnpierson** [comment]
Yes. Unfortunately the additional properties are only kept in 2.12 and up

**Comment by chuncahk** [comment]
Can this problem be solved by adding a txt file along with the dyn script?
if no txt presented, then it will shows the path by default

**Comment by johnpierson** [comment]
Hi @chunchk , When I get this feature added it will utilize the built-in graph description introduced in Dynamo 2.12, first. For versions prior to 2.12, I do like the txt idea because that does not require the plugin to search for a specific note. Let me ponder on that a bit more.

**Comment by johnpierson** [comment]
So here is a _quick_ mockup of what I was thinking for all currently supported Revit versions for relay (Revit 2021 - 2023).

The description is available in Dynamo's UI now through the Graph Properties extension.
![image](https://user-images.githubusercontent.com/15744724/183756379-a109da97-a246-4ddf-b7bc-705683e9b3b4.png)


And this would result in this:
![image](https://user-images.githubusercontent.com/15744724/183756155-645d3d06-6d91-4e71-aff3-02bfcda857b9.png)

The part of this that is required moving forward (and backward) is I have to have the file path in the tooltip with how relay loads a DYN right now.

Once again, this would work for Revit 2021 - 2023. Any older than that, the tooltips would not show up.

**Comment by bobarakatx** [comment]
This is not working in the latest Relay version. Revit 2023.1.3
